### ISSUE TITLE
Failed to read Docker file

### ISSUE THREAD

**Issue by thanone2** [gazzamc/decky-loader-windows#2]
![image](https://github.com/gazzamc/decky-loader-windows/assets/121321813/5bd3f023-7eb2-42df-9190-00e990ac8bfd)
idk what to do

**Comment by gazzamc** [comment]
Hi,

Can you confirm that the `Dockerfile` is within the `Steam Deck` folder? if so maybe also retry in a folder without spaces.

**Comment by thanone2** [comment]
sorry, forgot to take this down, the newest version of docker isn't compatible, so I ran the next version down and it went fine. And I also did what you said too.
